/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SummaryRouteImport } from './routes/summary'
import { Route as RootCauseRouteImport } from './routes/root-cause'
import { Route as ProductSizeRouteImport } from './routes/product-size'
import { Route as OverviewRouteImport } from './routes/overview'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AllRecordsRouteImport } from './routes/all-records'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const SummaryRoute = SummaryRouteImport.update({
  id: '/summary',
  path: '/summary',
  getParentRoute: () => rootRouteImport,
} as any)
const RootCauseRoute = RootCauseRouteImport.update({
  id: '/root-cause',
  path: '/root-cause',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSizeRoute = ProductSizeRouteImport.update({
  id: '/product-size',
  path: '/product-size',
  getParentRoute: () => rootRouteImport,
} as any)
const OverviewRoute = OverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AllRecordsRoute = AllRecordsRouteImport.update({
  id: '/all-records',
  path: '/all-records',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/all-records': typeof AllRecordsRoute
  '/auth': typeof AuthRoute
  '/overview': typeof OverviewRoute
  '/product-size': typeof ProductSizeRoute
  '/root-cause': typeof RootCauseRoute
  '/summary': typeof SummaryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/all-records': typeof AllRecordsRoute
  '/auth': typeof AuthRoute
  '/overview': typeof OverviewRoute
  '/product-size': typeof ProductSizeRoute
  '/root-cause': typeof RootCauseRoute
  '/summary': typeof SummaryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/all-records': typeof AllRecordsRoute
  '/auth': typeof AuthRoute
  '/overview': typeof OverviewRoute
  '/product-size': typeof ProductSizeRoute
  '/root-cause': typeof RootCauseRoute
  '/summary': typeof SummaryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/all-records'
    | '/auth'
    | '/overview'
    | '/product-size'
    | '/root-cause'
    | '/summary'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/all-records'
    | '/auth'
    | '/overview'
    | '/product-size'
    | '/root-cause'
    | '/summary'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/all-records'
    | '/auth'
    | '/overview'
    | '/product-size'
    | '/root-cause'
    | '/summary'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AllRecordsRoute: typeof AllRecordsRoute
  AuthRoute: typeof AuthRoute
  OverviewRoute: typeof OverviewRoute
  ProductSizeRoute: typeof ProductSizeRoute
  RootCauseRoute: typeof RootCauseRoute
  SummaryRoute: typeof SummaryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/summary': {
      id: '/summary'
      path: '/summary'
      fullPath: '/summary'
      preLoaderRoute: typeof SummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/root-cause': {
      id: '/root-cause'
      path: '/root-cause'
      fullPath: '/root-cause'
      preLoaderRoute: typeof RootCauseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product-size': {
      id: '/product-size'
      path: '/product-size'
      fullPath: '/product-size'
      preLoaderRoute: typeof ProductSizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overview': {
      id: '/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof OverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/all-records': {
      id: '/all-records'
      path: '/all-records'
      fullPath: '/all-records'
      preLoaderRoute: typeof AllRecordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AllRecordsRoute: AllRecordsRoute,
  AuthRoute: AuthRoute,
  OverviewRoute: OverviewRoute,
  ProductSizeRoute: ProductSizeRoute,
  RootCauseRoute: RootCauseRoute,
  SummaryRoute: SummaryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
